Variables:
  omp_num_threads: 12
  max_ball_count: 200
  WIDTH : 1600
  HEIGHT : 900
  animation_ticks : 8
  delta : 0.01
  max_radius : 15
  min_radius : 12
  max_frame_time : 1
  GRID_X : 4
  GRID_Y : 4

Options:
  cursor_interaction: 0 #Could be 1 or 0