Variables:
  omp_num_threads: 1
  max_ball_count: 100
  WIDTH : 1600
  HEIGHT : 900
  animation_ticks : 8
  delta : 0.01
  max_radius : 15
  min_radius : 12
  max_fps : 1000
  GRID_X : 1
  GRID_Y : 1

Options:
  cursor_interaction: 0 #Could be 1 or 0