Variables:
  omp_num_threads: 12
  max_ball_count: 2000
  WIDTH : 1600
  HEIGHT : 900
  animation_ticks : 8
  delta : 0.01
  max_radius : 15
  min_radius : 12
  max_fps : 1000
  GRID_X : 10
  GRID_Y : 10

Options:
  cursor_interaction: 0 #Could be 1 or 0